### PR TITLE
127 adjusted light of the flashlight

### LINKED ISSUE #127: [Design] - adjust area of flashlight
Make area of light wider.

### PR DESCRIPTION
**Pull request by DashaShev**
image

Close #127

### CODE REVIEW

**Comment by VladAdGad** [comment]
What do you think about the center of effect light on the monitor?

**Comment by VladAdGad** [comment]
and you don't apply it like prefab

**Comment by DashaShev** [comment]
Done

**Comment by VladAdGad** [comment]
@DashaShev you have conflicts because I applied FPSController from old changes. Resolve them if you have time

**Pull request closed without merging**
